services:
  hermes-agent:
    # Bagian 'build' dan 'context' DIHAPUS
    image: ghcr.io/khamami13/hermes-agent-netops:latest # Ubah nama image ke GitHub
    container_name: hermes-agent
    restart: unless-stopped
    network_mode: host
    command: gateway run
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    environment:
      TZ: Asia/Jakarta
      HERMES_DASHBOARD: "0"
    volumes:
      - /opt/junkielab/hermes-agent/data:/opt/data
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_RAW
      - NET_ADMIN
